### ISSUE TITLE
Typo in Lilex Medium

### ISSUE THREAD

**Issue by amberstarlight** [mishamyrt/Lilex#12]
Hey 👋🏻 really like this font, I'm using it on my website!

Just wanted to highlight that somewhere in your project you've got the medium weight misspelled as `"Meduim"` which is getting built out to `Lilex-Meduim.ttf`, and in font pickers, `Lilex Meduim`.

From a quick search of the repo, it looks like it's in `Lilex.gylphs`, [line 126344](https://github.com/mishamyrt/Lilex/blob/6de21bfa221564e8694f281c663f16ab93b76c33/Lilex.glyphs#L126344).

![Screenshot_20230630_204223](https://github.com/mishamyrt/Lilex/assets/14945391/a010710b-a2c9-40a8-851b-cb4333362057)

**Comment by mishamyrt** [comment]
Hi, thanks very much for the report. Fixed the bug, will be included in next patch release (2.210). 

It will be released when I fix #11, I plan to do it soon.
