### ISSUE TITLE
The => ligature is rendered incorrectly when used "Medium" weight

### ISSUE THREAD

**Issue by jimf5** [mishamyrt/Lilex#34]
The => ligature is rendered incorrectly when using "Medium" weight. I see it on Win11.
Here is example: 
![image](https://github.com/mishamyrt/Lilex/assets/54681898/01cfcefb-f807-49b1-a064-93b0c16b5449)

**Comment by mishamyrt** [comment]
This is the same problem that is reported in #11 . I'm working on a solution
