### ISSUE TITLE
ß character improved readability for german text

### ISSUE THREAD

**Issue by kumraa-1** [mishamyrt/Lilex#37]
I'd like to suggest to improve the ß characters readability.
In the german language it's a common letter and the currect character design hurts readability a lot.
The attached image is a comparison of Lilex and Monospace.
![comparison](https://github.com/user-attachments/assets/53de71fd-2722-495d-8146-bdf163914633)

**Comment by kumraa-1** [comment]
Thank you very much! This was the one gripe that kept me from using ibm plex mono in the end. I was so happy to find Lilex especially because of the more readable numbers.

**Comment by mishamyrt** [comment]
I'm not a big expert in German, so I need some advice. Can you tell me which of these options looks more familiar to modern German fonts?

<img src="https://github.com/user-attachments/assets/718cff1c-0ea6-4bf2-ac16-e9cc4c32b76c" width="300" />

**Comment by kumraa-1** [comment]
Wow you're quick!
The first variant looks very good. This is how the letter is used in german fonts.
I've never seen it drawn like the second variant but it seems like in very old typefaces it was sometimes used like that but I'd go with the first one.

Beware, there's also a capital ẞ
https://en.wikipedia.org/wiki/%C3%9F#Development_of_a_capital_form

**Comment by mishamyrt** [comment]
Could you check the different texts on the [font's demonostration page](https://preview--lilex.netlify.app/)? In the sidebar on the right you will find ß variants, you can compare them

**Comment by kumraa-1** [comment]
Yes, thank you, very good work!
