### ISSUE TITLE
Method to obtain OTF formats for Windows users

### ISSUE THREAD

**Issue by Quorsor** [mishamyrt/Lilex#8]
I don't know exactly if building the font in Windows is on the roadmap, but for the current update, there is no method of obtaining .otf formats of the font for features such as ligatures.

**Comment by coryzibell** [comment]
@Quorsor nerdfonts has patched Lilex otf fonts that work on windows, see their current release here:

https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

**Comment by mishamyrt** [comment]
Ligatures and other features are available in TTF, I see no reason to support OTF. Ligatures and other features are available in TTF, I see no reason to support OTF. If you need OTF as a matter of principle, use Docker or WSL2, you can reproduce the build there.
