### ISSUE TITLE
Support italic style from IBM Plex Mono

### ISSUE THREAD

**Issue by ginkcode** [mishamyrt/Lilex#9]
I really like the italic style from IBM Plex Mono. Can we have it in Lilex?

<img width="895" alt="Lilex" src="https://github.com/mishamyrt/Lilex/assets/9301098/b8135cad-2811-49c0-b42f-b483143164b9">
<img width="896" alt="Plex" src="https://github.com/mishamyrt/Lilex/assets/9301098/42860396-456e-4c4d-9e19-3a8cdd9fe1f8">

**Comment by mishamyrt** [comment]
To fully add italics, you need to redraw all the ligatures so that they match. That's 90 static ligatures and 57 sequences for compound ligatures.

I would also like italics, but unfortunately I don't have that much time.

**Comment by mishamyrt** [comment]
I'm marking this problem as `wontfix' for now, maybe I'll have some extra time (or someone will come along to help me) at some point.

**Comment by trepidacious** [comment]
Could there be a version with italics but no italic ligatures? Seems like in a lot of syntax highlighting italics aren't much used for operators/punctuation where ligatures occur, often it's just comments and identifiers. I was looking at how to do this but it seems fiddly enough that it might be helpful to have it done here, maybe as an extra download so it's optional?

**Comment by asjadjawed** [comment]
> I'm marking this problem as `wontfix' for now, maybe I'll have some extra time (or someone will come along to help me) at some point.

BTW, thank you for doing this awesome work 😊
